apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crossplane-ui.serviceAccountName" (dict "ctx" . "component" "gateway") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crossplane-ui.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crossplane-ui.serviceAccountName" (dict "ctx" . "component" "auth") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crossplane-ui.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth
